services:
  devops-project-2-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend_net
    environment:
      - NEXT_PUBLIC_API_URL=/api
    depends_on:
      - devops-project-2-backend

  devops-project-2-backend:
    build: ./backend
    expose:
      - "5000"
    networks:
      - frontend_net
      - backend_net
    environment:
      - FLASK_ENV=production

networks:
  frontend_net:
  backend_net:
    internal: true
